import type { Metadata } from "next";
import "./globals.css";
import { Providers } from '../store/providers';
import { ToastProvider, ThemeProvider } from '@/lib';

export const metadata: Metadata = {
  title: "Extreme Solution Hiring Challenge",
  description: "Generated by Mohanad Hassan",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
          <ThemeProvider>
            <ToastProvider />
            {children}
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
